# This is a simple theme config file

site_favicon: favicon.ico
name: About me
title: Tomáš Chalupa
logo: "/docs/assets/blurred_bg_light.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Hi and welcome!
  <br><br> 
  <a href="https://www.linkedin.com/in/tom%C3%A1%C5%A1-chalupa-26a578240/">LinkedIn</a> | <a href="https://www.instagram.com/tomass.ch/">Instagram</a> |
  <a href="https://open.spotify.com/user/bakedbrain?si=51edbb75e0824111/">Spotify</a>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
