# This is a simple theme config file

name: About me
logo: "/docs/assets/" # your photo (or logo) here
site_favicon: favicon.ico
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Hi and welcome!
  <br><br> 
  <a href="https://www.linkedin.com/in/tom%C3%A1%C5%A1-chalupa-26a578240/">LinkedIn</a> | <a href="https://www.instagram.com/tomass.ch/">Instagram</a>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
